[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
globecoin = "upgpSaYnMQRqiQYKc2LVw5EvD9JJBj5UtmpUFJGjaHM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vincent-ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
